Explain Action Run Conditions
opensafely/job-server pull request #231
Opened 2020-11-25 10:05 UTC by ghickman

This add help text blocks to both the Actions list and the Force Run Dependencies toggle to explain how a Users selections affect how their chose Actions are run.

![](https://p198.p4.n0.cdn.getcloudapp.com/items/5zudpqbb/Image%202020-11-25%20at%2010.01.48%20am.jpg?v=4dcda1a6b0645b9ac11e8f5ab74d6160)

> run_all will run all dependencies

Since `run_all` is defined by a User in their project.yaml (ie not something we do for them currently), should we still include this part?

Fixes #198

2020-11-25 10:08 UTC, evansd commented
V2 handles run_all and ignores any user defined action of that name. Eventually we should bump the project.yaml version and make it an error to define a run_all action

2020-11-25 10:45 UTC, sebbacon requested changes
So in v2 we'll need to special-case `run_all` because we still want it to be selectable even though it doesn't appear in the `project.yaml`?

2020-11-25 10:45 UTC, sebbacon commented on jobserver/templates/workspace_detail.html
> +          Selecting an Action will run it, regardless of it's previous state or outputs.
`its`

2020-11-25 10:45 UTC, sebbacon commented on jobserver/templates/workspace_detail.html
> +          Selecting this will run each Action in your selected Actions
`Action's`

2020-11-25 10:50 UTC, ghickman commented on jobserver/templates/workspace_detail.html
> +          Selecting an Action will run it, regardless of it's previous state or outputs.
Fixed and rebased in 1706032

2020-11-25 10:50 UTC, ghickman commented on jobserver/templates/workspace_detail.html
> +          Selecting this will run each Action in your selected Actions
Fixed and rebased in 1706032

2020-11-25 10:54 UTC, ghickman commented
@evansd – will having `run_all` in the `requested_actions` field continue to work as expected?  I can easily modify the UI if that's the case.

2020-11-25 10:59 UTC, evansd commented
Yes, absolutely. You can basically pretend run_all is a normal action like any other. It just always exists whether you've defined it or not.

2020-11-25 11:02 UTC, ghickman commented
Captured in #234

2020-11-26 14:02 UTC, ghickman commented
@sebbacon – this one is good to go now I think?

2020-11-26 14:09 UTC, sebbacon approved these changes

2020-11-26 15:13 UTC, merged